Play lightsaber sound
team-prstmw/StarWarsQuiz pull request #12
Opened 2021-12-11 22:52 UTC by ike-tom

Added a function that plays any sound based on the given path.

2021-12-17 20:04 UTC, PatrykJurczyk requested changes

2021-12-23 22:27 UTC, ike-tom commented on src/playSound.js
> +  const audio = new Audio(soundPath);
I don't think it's necessary in this case.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio

'The new object's preload property is set to auto and its src property is set to the specified URL or null if no URL is given. If a URL is specified, the browser begins to asynchronously load the media resource before returning the new object. '

2021-12-23 22:28 UTC, ike-tom commented
to test this function just add to the main.js, then click on the first button.

import playSound from './playSound';

const btn = document.querySelector('.btn');
btn.addEventListener('click', () => {
  playSound('../assets/sounds/lightsaberSound.mp3');
});

2021-12-24 07:15 UTC, PatrykJurczyk approved these changes

2021-12-28 18:38 UTC, mgoniszewska approved these changes

2021-12-29 23:39 UTC, merged