Quiz page
team-prstmw/StarWarsQuiz pull request #14
Opened 2021-12-19 15:54 UTC by shadowas-py

2021-12-19 18:48 UTC, FilipHalon requested changes

2021-12-19 18:48 UTC, FilipHalon commented on src/quiz_page_elements/Answer.js
> +export default class Answer {
This component and `Question.js` could shortened by extending `HTmlElement` like this:
```
import HtmlElement from '../components/htmlElement/HtmlElement';
import './answer.css';

export default class Answer extends HtmlElement {
  constructor(label) {
    super(['quiz-answer'], 'div', label);
  }
}
```

2021-12-19 22:00 UTC, FilipHalon approved these changes

2021-12-19 22:00 UTC, FilipHalon commented on src/quizPageElements/quizContainer.css
> +@media only screen and (max-width: 360px) {
Please apply `mobile first` breakpoints like `@media only screen and (min-width: 360px/768px/992px/1400px)` before merging.

2021-12-22 20:39 UTC, PatrykJurczyk approved these changes

2021-12-22 21:40 UTC, merged