Added Game Over Modal with logic
team-prstmw/StarWarsQuiz pull request #16
Opened 2021-12-21 00:13 UTC by mgoniszewska

2021-12-22 21:06 UTC, FilipHalon requested changes

2021-12-22 21:06 UTC, FilipHalon commented on src/layouts/GameOverModal/styles.css
> +    position: absolute;
You don't have to redeclare styles if they are the same as above. Styles concerning an element that are lowest in a file will be the ones a browser uses and this includes media queries.

2021-12-26 17:39 UTC, mgoniszewska commented on src/layouts/GameOverModal/GameOverModal.js
> +import Button from '../../components/button/Button';
I noticed that we don't use absolute imports at all. How can we do it in this project? I read on stackoverflow that we should have configuration in vite for it. Maybe you can configure it and then we will update our imports.

2021-12-26 19:58 UTC, FilipHalon commented on src/layouts/GameOverModal/GameOverModal.js
> +import Button from '../../components/button/Button';
Right. As we discussed, let's leave it relative as long as we don't configure Vite for it.

2021-12-26 20:17 UTC, FilipHalon approved these changes

2021-12-26 20:17 UTC, FilipHalon commented on src/layouts/GameOverModal/GameOverModal.js
> +    yodaImage.src = '../../images/Yoda.png';
This still could be shortened to `'/images/Yoda.png'`.

2021-12-26 23:18 UTC, ike-tom commented
Modal is not centered in the middle of the page on mobiles

2021-12-26 23:24 UTC, ike-tom requested changes
One comment from github+ I wrote you more on discord

2021-12-29 23:40 UTC, ike-tom approved these changes

2021-12-30 10:23 UTC, merged