Added sabre to quizPage
team-prstmw/StarWarsQuiz pull request #33
Opened 2022-01-04 19:55 UTC by PatrykJurczyk

2022-01-04 20:30 UTC, FilipHalon requested changes

2022-01-04 20:30 UTC, FilipHalon commented on styles/index.css
>    grid-template-rows: auto 1fr;
The saber overlaps with the quiz on tablets and smaller screens. To keep it always below the quiz, you could set `grid-template-rows` to something like `1fr auto 0.2fr` and remove `position: relative` and `top` properties from `#lightSabreProgresBar`. Consider also changing the height of the `img` to make the saber and the time counter closer to the quiz.

2022-01-04 23:49 UTC, FilipHalon approved these changes

2022-01-04 23:49 UTC, FilipHalon commented on src/components/timeSabarCounter/saberTime.js
> +      // removeElement('#lightSabreProgresBar')
You could remove these comments.

2022-01-04 23:49 UTC, FilipHalon commented on styles/index.css
> -  display: flex;
This should stay, as it makes the content stay centered on wider screens.

2022-01-04 23:49 UTC, FilipHalon commented on styles/menu.css
> +@media screen{
I guess you could delete this media query.

2022-01-05 13:09 UTC, mgoniszewska approved these changes

2022-01-05 13:20 UTC, merged